exports.tracklist = [
    {
        "trackname":"Paradise",
        "artists":"MVLLER, Kashwell, Melk",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Move On",
        "artists":"SEK Music Group, MVLLER, π, Dominika Ihász",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"I'm Good (MVLLER Remix)",
        "artists":"David Guetta, Bebe Rexha, MVLLER",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"she's all i wanna be (MVLLER Remix)",
        "artists":"Tate McRae, MVLLER",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"abcdefu (MVLLER Remix)",
        "artists":"GAYLE, MVLLER",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Moth To A Flame (MVLLER Remix)",
        "artists":"Swedish House Mafia, The Weeknd, MVLLER",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Pink Soldiers (MVLLER Remix)",
        "artists":"Squid Game, MVLLER",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"All On Me (MVLLER's Future Rave Remix)",
        "artists":"Tchami, ZHU, MVLLER",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Unbreakable (MVLLER's Future Rave Remix)",
        "artists":"BUNT., Clarence Coffee Jr., MVLLER",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Party In The 90's",
        "artists":"MVLLER, BnD",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Rave Addiction",
        "artists":"MVLLER",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Daddy Cool (MVLLER Remix)",
        "artists":"Boney M, MVLLER",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Thunderstorm",
        "artists":"MVLLER",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Freedom",
        "artists":"MVLLER",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Imagine",
        "artists":"MVLLER",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Messy (Müller Remix)",
        "artists":"Kiiara, Müller",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Tell Me You Love Me (Müller Remix)",
        "artists":"Galantis, Throttle, Müller",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Ain't Nobody Got Time For That (Müller Remix)",
        "artists":"Sweet Brown, Müller",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Without You (Müller Remix)",
        "artists":"Avicii, Müller",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Memories",
        "artists":"Müller",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Planet",
        "artists":"Müller",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"XP",
        "artists":"Müller",
        "coverSrc":"",
        "audioSrc":"",
    },
    {
        "trackname":"Just Smile",
        "artists":"Müller",
        "coverSrc":"",
        "audioSrc":"",
    }
]